// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RentalManagementSystem.Data;

#nullable disable

namespace RentalManagementSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241118054747_NewDbCreation")]
    partial class NewDbCreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RentalManagementSystem.Models.PropertyModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BlockNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("UnitNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BlockNumber = "A",
                            Price = 100f,
                            UnitNumber = 1
                        },
                        new
                        {
                            Id = 2,
                            BlockNumber = "A",
                            Price = 100f,
                            UnitNumber = 2
                        });
                });

            modelBuilder.Entity("RentalManagementSystem.Models.RenterModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("Renters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Hao",
                            PropertyId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Hoa",
                            PropertyId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Hai",
                            PropertyId = 2
                        });
                });

            modelBuilder.Entity("RentalManagementSystem.Models.RenterModel", b =>
                {
                    b.HasOne("RentalManagementSystem.Models.PropertyModel", "Property")
                        .WithMany("Renters")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("RentalManagementSystem.Models.PropertyModel", b =>
                {
                    b.Navigation("Renters");
                });
#pragma warning restore 612, 618
        }
    }
}
